runtime: nodejs20
service: default  # or your specific service name
env: flex  # recommended for TypeScript projects

# Environment variables (if needed)
env_variables:
  NODE_ENV: production

# For Node.js flexible environment
manual_scaling:
  instances: 1

# Health checks
health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2