steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  
  # Build the project
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build:prod']
  
  # Run tests (optional)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test:ci']
    env:
      - 'NODE_ENV=test'
  
  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']
    timeout: '1200s'

# Timeout for the entire build
timeout: '1800s'

# Optional: Cache node_modules between builds
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  env:
    - 'NODE_ENV=production'